//! TEMPLATE
if has("gui_running")
	set guifont={FONT_MONOSPACE}\ {FONT_SIZE}
	set guioptions-=m "Turn off the menu bar
	set guioptions-=T "Turn off the tool bar
	set guioptions-=L "Turn off the left scroll bar
	set guioptions-=r "Turn off the right scroll bar

	set background=dark
	colorscheme solarized
endif

syntax on
set list
set number
set ruler

let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files']
